---
- homebrew: name={{ item }} state=latest
  with_items:
    - openssl
    - libyaml
# required for building Ruby <= 1.9.3-p0
- homebrew_tap: tap=homebrew/dupes state=present
  when: rbenv.ruby_version <= 1.9.3-p0
- homebrew: name=apple-gcc42 state=latest
  when: rbenv.ruby_version <= 1.9.3-p0